import axios from "axios";

export const get_bible_data = () => dispatch => {
    axios.get("/api/asv/genesis/1/")
        .then(response => {
            dispatch({
                payload: response.data
            })
        }).catch(errors => console.log(errors))
}

export const availableVersions = [
    {
        name: "SISWATI",
        full_name: "Siswati Version",
        short: "siswati",
        goto_link: "/api/kjv/",
        first_book: "Genesisi"
    },
    {
        name: "ASV",
        full_name: "American Standard Version",
        short: "asv",
        goto_link: "/api/kjv",
        first_book: "Genesis"
    },
    {
        name: "BBE",
        full_name: "Bible in Basic English",
        short: "bbe",
        goto_link: "/api/kjv",
        first_book: "Genesis"
    },
    {
        name: "KJV",
        full_name: "King James Version",
        short: "kjv",
        goto_link: "/api/kjv",
        first_book: "Genesis"
    },
    {
        name: "NIV",
        full_name: "New Internation Version",
        short: "niv",
        goto_link: "/api/kjv",
        first_book: "Genesis"
    },
    {
        name: "WBT",
        full_name: "World English Bible",
        short: "wbt",
        goto_link: "/api/kjv",
        first_book: "Genesis"
    },
    {
        name: "YLT",
        full_name: "Young's Literal Translation",
        short: "ylt",
        goto_link: "/api/kjv",
        first_book: "Genesis"
    },
    {
        name: "ZULU",
        full_name: "Sizulu",
        short: "zulu",
        goto_link: "/api/kjv",
        first_book: "Genesise"
    }
]


export const ENGLISH_BOOKS = {
    "Genesis": 50,
    "Exodus": 40,
    "Leviticus": 27,
    "Numbers": 36,
    "Deuteronomy": 34,
    "Joshua": 24,
    "Judges": 21,
    "Ruth": 4,
    "1 Samuel": 31,
    "2 Samuel": 24,
    "1 Kings": 22,
    "2 Kings": 25,
    "1 Chronicles": 29,
    "2 Chronicles": 36,
    "Ezra": 10,
    "Nehemiah": 13,
    "Esther": 10,
    "Job": 42,
    "Psalms": 150,
    "Proverbs": 31,
    "Ecclesiastes": 12,
    "Song of Solomon": 8,
    "Isaiah": 66,
    "Jeremiah": 52,
    "Lamentations": 5,
    "Ezekiel": 48,
    "Daniel": 12,
    "Hosea": 14,
    "Joel": 3,
    "Amos": 9,
    "Obadiah": 1,
    "Jonah": 4,
    "Micah": 7,
    "Nahum": 3,
    "Habakkuk": 3,
    "Zephaniah": 3,
    "Haggai": 2,
    "Zechariah": 14,
    "Malachi": 4,
    "Matthew": 28,
    "Mark": 16,
    "Luke": 24,
    "John": 21,
    "Acts": 28,
    "Romans": 16,
    "1 Corinthians": 16,
    "2 Corinthians": 13,
    "Galatians": 6,
    "Ephesians": 6,
    "Philippians": 4,
    "Colossians": 4,
    "1 Thessalonians": 5,
    "2 Thessalonians": 3,
    "1 Timothy": 6,
    "2 Timothy": 4,
    "Titus": 3,
    "Philemon": 1,
    "Hebrews": 13,
    "James": 5,
    "1 Peter": 5,
    "2 Peter": 3,
    "1 John": 5,
    "2 John": 1,
    "3 John": 1,
    "Jude": 1,
    "Revelation": 22,
}

export const SISWATI_BOOKS = {
    "Genesisi": 50,
    "Eksodusi": 40,
    "Levithikusi": 27,
    "Numeri": 36,
    "Dutheronomi": 34,
    "Joshuwa": 24,
    "Tikhulu": 21,
    "Ruthe": 4,
    "1 Samuweli": 31,
    "2 Samuweli": 24,
    "1 Emakhosi": 22,
    "2 Emakhosi": 25,
    "1 Tikhronike": 29,
    "2 Tikhronike": 36,
    "Ezra": 10,
    "Nehemiya": 13,
    "Esta": 10,
    "Jobe": 42,
    "Tihlabelelo": 150,
    "Taga": 31,
    "Umshumayeli": 12,
    "Ingoma Yetingoma": 8,
    "Isaya": 66,
    "Jeremiya": 52,
    "Sililo": 5,
    "Hezekeli": 48,
    "Danyela": 12,
    "Hoseya": 14,
    "Joweli": 3,
    "Amose": 9,
    "Obadiya": 1,
    "Jona": 4,
    "Mikha": 7,
    "Nahume": 3,
    "Habakhuki": 3,
    "Zefaniya": 3,
    "Hagayi": 2,
    "Zakhariya": 14,
    "Malakhi": 4,
    "Matewu": 28,
    "Makho": 16,
    "Lukha": 24,
    "Johane": 21,
    "Imisebenti yebaPhostoli": 28,
    "KubaseRoma": 16,
    "1 kubaseKorinthe": 16,
    "2 kubaseKorinthe": 13,
    "KubaseGalathiya": 6,
    "Kubase-Efesu": 6,
    "KubaseFiliphi": 4,
    "KubaseKholose": 4,
    "1 kubaseThesalonika": 5,
    "2 kubaseThesalonika": 3,
    "1 kuThimothi": 6,
    "2 kuThimothi": 4,
    "kuThithusi": 3,
    "kuFilemoni": 1,
    "KumaHebheru": 13,
    "YaJakobe": 5,
    "1 yaPhetro": 5,
    "2 yaPhetro": 3,
    "1 yaJohane": 5,
    "2 yaJohane": 1,
    "3 yaJohane": 1,
    "YaJuda": 1,
    "Sembulo": 22,
}

export const SIZULU_BOOKS = {
    "Genesise": 50,
    "Eksodusi": 40,
    "Levitikusi": 27,
    "Numeri": 36,
    "Duteronomi": 34,
    "Joshuwa": 24,
    "AbAhluleli": 21,
    "Ruthe": 4,
    "1 Samuweli": 31,
    "2 Samuweli": 24,
    "1 AmaKhosi": 22,
    "2 AmaKhosi": 25,
    "1 IziKronike": 29,
    "2 IziKronike": 36,
    "Ezra": 10,
    "Nehemiya": 13,
    "Esteri": 10,
    "Jobe": 42,
    "AmaHubo": 150,
    "IzAga": 31,
    "UmShumayeli": 12,
    "IsiHlabelelo SeziHlabelelo": 8,
    "Isaya": 66,
    "Jeremiya": 52,
    "IsiLilo": 5,
    "Hezekeli": 48,
    "Daniyeli": 12,
    "Hoseya": 14,
    "Joweli": 3,
    "Amose": 9,
    "Obadiya": 1,
    "Jona": 4,
    "Mika": 7,
    "Nahume": 3,
    "Habakuki": 3,
    "Zefaniya": 3,
    "Hagayi": 2,
    "Zakariya": 14,
    "Malaki": 4,
    "Mathewu": 28,
    "Marku": 16,
    "Luka": 24,
    "Johane": 21,
    "IzEnzo": 28,
    "AmaRoma": 16,
    "1 Korinte": 16,
    "2 Korinte": 13,
    "Galathiya": 6,
    "Efesu": 6,
    "Filipi": 4,
    "Kolose": 4,
    "1 Thesalonika": 5,
    "2 Thesalonika": 3,
    "1 Thimothewu": 6,
    "2 Thimothewu": 4,
    "KuThithu": 3,
    "KuFilemoni": 1,
    "KumaHeberu": 13,
    "EkaJakobe": 5,
    "1 Petru": 5,
    "2 Petru": 3,
    "1 Johane": 5,
    "2 Johane": 1,
    "3 Johane": 1,
    "EkaJuda": 1,
    "IsAmbulo": 22,
}

