# Generated by Django 3.1.5 on 2022-02-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_number', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('verse_text', models.TextField()),
            ],
            options={
                'db_table': 't_asv',
            },
        ),
        migrations.CreateModel(
            name='Bbe',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('book_number', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('verse_text', models.TextField()),
            ],
            options={
                'db_table': 't_bbe',
            },
        ),
        migrations.CreateModel(
            name='BibleVersionKey',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tables', models.TextField()),
                ('abbreviation', models.TextField()),
                ('language', models.TextField()),
                ('version', models.TextField()),
            ],
            options={
                'db_table': 'bible_version_key',
            },
        ),
        migrations.CreateModel(
            name='KeyEnglish',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('chapters_count', models.IntegerField()),
            ],
            options={
                'db_table': 'key_english',
            },
        ),
        migrations.CreateModel(
            name='Kjv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_number', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('verse_text', models.TextField()),
            ],
            options={
                'db_table': 't_kjv',
            },
        ),
        migrations.CreateModel(
            name='Niv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_number', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('verse_text', models.TextField()),
            ],
            options={
                'db_table': 't_niv',
            },
        ),
        migrations.CreateModel(
            name='Siswati',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_number', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('verse_text', models.TextField()),
            ],
            options={
                'db_table': 't_siswati',
            },
        ),
        migrations.CreateModel(
            name='Wbt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_number', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('verse_text', models.TextField()),
            ],
            options={
                'db_table': 't_wbt',
            },
        ),
        migrations.CreateModel(
            name='Ylt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_number', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('verse_text', models.TextField()),
            ],
            options={
                'db_table': 't_ylt',
            },
        ),
        migrations.CreateModel(
            name='Zulu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_number', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('verse_text', models.TextField()),
            ],
            options={
                'db_table': 't_zulu',
            },
        ),
    ]
