BOOKS_ENGLISH = ['Genesis', 'Exodus', 'Leviticus', 'Numbers', 'Deuteronomy', 'Joshua', 'Judges', 'Ruth', '1 Samuel', '2 Samuel', '1 Kings', '2 Kings', '1 Chronicles', '2 Chronicles', 'Ezra', 'Nehemiah', 'Esther', 'Job', 'Psalms', 'Proverbs', 'Ecclesiastes', 'Song of Solomon', 'Isaiah', 'Jeremiah', 'Lamentations', 'Ezekiel', 'Daniel', 'Hosea', 'Joel', 'Amos', 'Obadiah', 'Jonah', 'Micah', 'Nahum', 'Habakkuk', 'Zephaniah', 'Haggai', 'Zechariah', 'Malachi', 'Matthew', 'Mark', 'Luke', 'John', 'Acts', 'Romans', '1 Corinthians', '2 Corinthians', 'Galatians', 'Ephesians', 'Philippians', 'Colossians', '1 Thessalonians', '2 Thessalonians', '1 Timothy', '2 Timothy', 'Titus', 'Philemon', 'Hebrews', 'James', '1 Peter', '2 Peter', '1 John', '2 John', '3 John', 'Jude', 'Revelation']
BOOKS_SISWATI = ['Genesisi', 'Eksodusi', 'Levithikusi', 'Numeri', 'Dutheronomi', 'Joshuwa', 'Tikhulu', 'Ruthe', '1 Samuweli', '2 Samuweli', '1 Emakhosi', '2 Emakhosi', '1 Tikhronike', '2 Tikhronike', 'Ezra', 'Nehemiya', 'Esta', 'Jobe', 'Tihlabelelo', 'Taga', 'Umshumayeli', 'Ingoma Yetingoma', 'Isaya', 'Jeremiya', 'Sililo', 'Hezekeli', 'Danyela', 'Hoseya', 'Joweli', 'Amose', 'Obadiya', 'Jona', 'Mikha', 'Nahume', 'Habakhuki', 'Zefaniya', 'Hagayi', 'Zakhariya', 'Malakhi', 'Matewu', 'Makho', 'Lukha', 'Johane', 'Imisebenti yebaPhostoli', 'KubaseRoma', '1 kubaseKorinthe', '2 kubaseKorinthe', 'KubaseGalathiya', 'Kubase-Efesu', 'KubaseFiliphi', 'KubaseKholose', '1 kubaseThesalonika', '2 kubaseThesalonika', '1 kuThimothi', '2 kuThimothi', 'kuThithusi', 'kuFilemoni', 'KumaHebheru', 'YaJakobe', '1 yaPhetro', '2 yaPhetro', '1 yaJohane', '2 yaJohane', '3 yaJohane', 'YaJuda', 'Sembulo']
BOOKS_ZULU = ['Genesise', 'Eksodusi', 'Levitikusi', 'Numeri', 'Duteronomi', 'Joshuwa', 'AbAhluleli', 'Ruthe', '1 Samuweli', '2 Samuweli', '1 AmaKhosi', '2 AmaKhosi', '1 IziKronike', '2 IziKronike', 'Ezra', 'Nehemiya', 'Esteri', 'Jobe', 'AmaHubo', 'IzAga', 'UmShumayeli', 'IsiHlabelelo SeziHlabelelo', 'Isaya', 'Jeremiya', 'IsiLilo', 'Hezekeli', 'Daniyeli', 'Hoseya', 'Joweli', 'Amose', 'Obadiya', 'Jona', 'Mika', 'Nahume', 'Habakuki', 'Zefaniya', 'Hagayi', 'Zakariya', 'Malaki', 'Mathewu', 'Marku', 'Luka', 'Johane', 'IzEnzo', 'AmaRoma', '1 Korinte', '2 Korinte', 'Galathiya', 'Efesu', 'Filipi', 'Kolose', '1 Thesalonika', '2 Thesalonika', '1 Thimothewu', '2 Thimothewu', 'KuThithu', 'KuFilemoni', 'KumaHeberu', 'EkaJakobe', '1 Petru', '2 Petru', '1 Johane', '2 Johane', '3 Johane', 'EkaJuda', 'IsAmbulo']


COLUMN_NIV_BOOK = "NIV_BOOK"
COLUMN_SISWATI_BOOK = "SISWATI_BOOK"
COLUMN_NIV_VERSE = "NIV_VERSE"
COLUMN_SISWATI_VERSE = "SISWATI_VERSE"

